[pytest]
addopts =
    --cov=survivalpfn --cov-report=term-missing --cov-config=pytest.ini

markers =
    integration: mark tests as integration tests.

norecursedirs =
    output
    wandb
    .git

filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
