"""Dataset splits and result schemas used for the SurvivalPFN paper release."""

PAPER_VALIDATION_DATASETS = [
    "ovarian",
    "glioma",
    "leukemia",
    "pharmacoSmoking",
    "d.oropha.rec",
    "Pbc3",
    "retinopathy",
    "Rossi",
    "phpl04K8a",
    "prostate",
    "uis",
    "grace",
    "rdata",
    "TRACE",
    "Aids2",
    "UnempDur",
    "smarto",
    "dataDIVAT1",
    "oldmort",
    "prostateSurvival",
]

PAPER_TEST_DATASETS = [
    "Bergamaschi",
    "larynx",
    "lupus",
    "micro.censure",
    "cgd",
    "veteran",
    "nki70",
    "stagec",
    "burn",
    "BMT",
    "WPBC",
    "Melanoma",
    "hepatoCellular",
    "cancer",
    "NCCTG",
    "mgus",
    "e1684",
    "HFCR",
    "ova",
    "diabetes",
    "PBC",
    "zinc",
    "Unemployment",
    "whas500",
    "cost",
    "BCCardiotox",
    "GBM",
    "vlbw",
    "GBSG2",
    "FRTCS",
    "kidney_transplant",
    "dataOvarian1",
    "colon",
    "credit",
    "PDM",
    "LeukSurv",
    "actg",
    "COVID",
    "WHAS",
    "dataDIVAT2",
    "scania",
    "churn",
    "METABRIC",
    "AIDS",
    "NACD",
    "rott2",
    "divorce",
    "acath",
    "NWTCO",
    "dataDIVAT3",
    "Framingham",
    "NPC",
    "Dialysis",
    "FLCHAIN",
    "MSKCC",
    "SUPPORT",
    "employee",
    "MIMIC-IV_all",
    "hdfail",
    "SEER_brain",
    "SEER_liver",
]

PAPER_DATASETS = [*PAPER_VALIDATION_DATASETS, *PAPER_TEST_DATASETS]

BENCHMARK_RESULTS_COLUMNS = [
    "model",
    "dataset",
    "metric",
    "mean",
    "std",
    "runtime_seconds",
]
SPLIT_RATIO_RESULTS_COLUMNS = [
    "model",
    "dataset",
    "training_ratio",
    "metric",
    "mean",
    "se",
]
ABLATION_RESULTS_COLUMNS = [
    "version",
    "prior",
    "time_transform",
    "loss",
    "query_schedule",
    "variable_train_ratio",
    "metric",
    "rank",
]
