# @package _global_
defaults:
  - _self_

model:
  obj:
    _target_: survivalpfn.models.InContextModel
    model:
      _target_: survivalpfn.models.TabDPTLongContextModel
      dropout: 0.0
      n_out: 10
      nbins: 1024
      nhead: 12
      nhid: 1536
      ninp: 768
      nlayers: 20
      num_features: 100
    sigma: ${sigma}
    vmin: ${vmin}
    vmax: ${vmax}
    query_strategy: ${query_strategy}
    time_transform: ${time_transform}
    model_config:
      model_type: tabdpt
      training:
        dropout: ${...model.dropout}
      model:
        max_num_classes: ${...model.n_out}
        nhead: ${...model.nhead}
        emsize: ${...model.ninp}
        nhid_factor: ${eval:'${...model.nhid} // ${...model.ninp}'}
        nlayers: ${...model.nlayers}
        max_num_features: ${...model.num_features}
        nbins: ${...model.nbins}
      env:
        device: ${default_device}
trainer:
  batch_size: 32
  num_agg: 8
compile: true
